---
name: paasta-portal                      # 서비스 배포이름(필수) bosh deployments 로 확인 가능한 이름

stemcells:
- alias: ((stemcell_alias))
  os: ((stemcell_os))
  version: "((stemcell_version))"
- alias: binary_storage_stemcells
  os: ((stemcell_os))
  version: 3468.51 



releases:
- name: "((releases_name))"                   # 서비스 릴리즈 이름(필수) bosh releases로 확인 가능
  version: "2.0"                                              # 서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

update:
  canaries: 1                                               # canary 인스턴스 수(필수)
  canary_watch_time: 5000-120000                            # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 5000-120000                            # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 1                                          # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  serial: false

instance_groups:




######## WEB SERVICE ########

- name: paas-ta-portal-gateway
  azs:
  - z6
  instances: 1
  vm_type: "((vm_type_small))"
  stemcell: "((stemcell_alias))"
  networks:
  - name: ((internal_networks_name))
  templates:
  - name: paas-ta-portal-gateway
    release: "((releases_name))"
  syslog_aggregator: null
  properties:
    java_opts: "-Xmx450m -Xss1M -XX:MaxMetaspaceSize=93382K -XX:ReservedCodeCacheSize=240m -XX:+UseCompressedOops -Djdk.tls.ephemeralDHKeySize=2048 -Dfile.encoding=UTF-8 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Xverify:none -XX:ErrorFile=/var/vcap/sys/log/java_error_in_idea_%p.log -XX:HeapDumpPath=/var/vcap/sys/log/java_error_in_idea.hprof"

- name: paas-ta-portal-registration
  azs:
  - z6
  instances: 1
  vm_type: "((vm_type_small))"
  stemcell: "((stemcell_alias))"
  networks:
  - name: ((internal_networks_name))
  templates:
  - name: paas-ta-portal-registration
    release: "((releases_name))"
  syslog_aggregator: null
  properties:
    java_opts: "-Xmx450m -Xss1M -XX:MaxMetaspaceSize=93382K -XX:ReservedCodeCacheSize=240m -XX:+UseCompressedOops -Djdk.tls.ephemeralDHKeySize=2048 -Dfile.encoding=UTF-8 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Xverify:none -XX:ErrorFile=/var/vcap/sys/log/java_error_in_idea_%p.log -XX:HeapDumpPath=/var/vcap/sys/log/java_error_in_idea.hprof"
    server:
      port: 2221


